insert into CUSTOMER (id, user_id, stripe_id, location_address, location_city, location_postal_code, location_latitude, location_longitude, payment_method, profile_image_id) values (1, 1, 'cus_C3khD5mPYki4Hs', '23 Crestwood Dr.', 'Cambridge', 'N1S3N8', 43.3440436, -80.3302874, 'VISA', 'GGLM4P8');
insert into CUSTOMER (id, user_id, stripe_id, location_address, location_city, location_postal_code, location_latitude, location_longitude, payment_method) values (2, 2, 'cus_C3kh05KMgcu0bX', '23 Crestwood Dr.', 'Cambridge', 'N1S3N8', 43.3440436, -80.3302874, 'AE');
insert into CUSTOMER (id, user_id, stripe_id, location_address, location_city, location_postal_code, location_latitude, location_longitude, payment_method) values (3, 3, 'cus_C3kiGsw3J8dDeu', '23 Crestwood Dr.', 'Cambridge', 'N1S3N8', 43.3440436, -80.3302874, 'MASTERCARD');
insert into CUSTOMER (id, user_id, stripe_id, location_address, location_city, location_postal_code, location_latitude, location_longitude, payment_method) values (4, 4, 'cus_C3kiZMp51iX3og', '23 Crestwood Dr.', 'Cambridge', 'N1S3N8', 43.3440436, -80.3302874, 'VISA');
insert into CUSTOMER (id, user_id, stripe_id, location_address, location_city, location_postal_code, location_latitude, location_longitude, payment_method) values (5, 5, 'cus_C3kiLg0du676H1', '23 Crestwood Dr.', 'Cambridge', 'N1S3N8', 43.3440436, -80.3302874, 'VISA');

insert into DRIVER (id, user_id, car_make, car_model, car_year, car_colour, car_plate) values (1, 1, 'Kia', 'Rio', '2015', 'Blue', 'BXEC 717'); 
insert into DRIVER (id, user_id, car_make, car_model, car_year, car_colour, car_plate, profile_image_id) values (2, 2, 'Subaru', 'Forester', '2012', 'Grey', '7I77 135', 'TmcAIWm');
insert into DRIVER (id, user_id, car_make, car_model, car_year, car_colour, car_plate) values (3, 3, 'Dodge', 'Grand Caravan', '2001', 'Tan', '7I77 135');
insert into DRIVER (id, user_id, car_make, car_model, car_year, car_colour, car_plate) values (4, 4, 'Mini Cooper', 'S', '2017', 'Red', '7I77 135');
insert into DRIVER (id, user_id, car_make, car_model, car_year, car_colour, car_plate) values (5, 5, 'Tesla', 'Model S', '2016', 'Black', '7I77 135');